FUNCTION Main()
  LOCAL lines := {}, nl := Chr(10), q := Chr(34)
  InsertLines(lines)
  AEval(lines, { |line| OutStd(line+nl) })
  AEval(lines, { |line| OutStd('  AAdd(lines, '+q+line+q+')'+nl) })

FUNCTION InsertLines(lines)
  AAdd(lines, "FUNCTION Main()")
  AAdd(lines, "  LOCAL lines := {}, nl := Chr(10), q := Chr(34)")
  AAdd(lines, "  InsertLines(lines)")
  AAdd(lines, "  AEval(lines, { |line| OutStd(line+nl) })")
  AAdd(lines, "  AEval(lines, { |line| OutStd('  AAdd(lines, '+q+line+q+')'+nl) })")
  AAdd(lines, "")
  AAdd(lines, "FUNCTION InsertLines(lines)")
